# Generated by Django 5.1 on 2024-11-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="is_abandoned",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="IN_PROGRESS",
                max_length=30,
            ),
        ),
    ]
