# Generated by Django 5.1 on 2024-12-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="trip",
            table="TRIP",
        ),
    ]
